#!/usr/bin/env php
<?php

define('VOYAGE_WORKING_DIR', __DIR__);

require VOYAGE_WORKING_DIR . '/vendor/autoload.php';
require VOYAGE_WORKING_DIR . '/lib/bootstrap.php';

use Voyage\Core\Application;

$application = new Application();
$application->run();