#!/usr/bin/env php
<?php

if (php_sapi_name() !== 'cli') {
    die('This tool should be executed only from command-line interface.');
}

define('VOYAGE_WORKING_DIR', getcwd());

require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/lib/bootstrap.php';

use Voyage\Core\Application;

$application = new Application();
$application->run();